imas/imasparql

- RDFs/Disc.rdf
入れ子の中の子要素に型(rdf:datatype)を付けたければ独立させろと...
> schema:MusicReleaseをMusicAlbumの入れ子から独立(必須)

- RDFs/CinderellaGirls.rdf
出典:[ニコ百科シンデレラガールズ声優の一覧](http://dic.nicovideo.jp/a/%E3%82%B7%E3%83%B3%E3%83%87%E3%83%AC%E3%83%A9%E3%82%AC%E3%83%BC%E3%83%AB%E3%82%BA%E5%A3%B0%E5%84%AA%E3%81%AE%E4%B8%80%E8%A6%A7)
早坂美玲はまだ書いてません
> デレのCV(と氏家むつみの名前が無かった)

- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
> gMonthDay書式に沿う

- RDFs/CinderellaGirls.rdf
- RDFs/Song.rdf
> Warn solve

- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
xml:lang="ja/en"と書いていたけど、datatypeも書かないといけない
> Stringと明記されていないdatatypeの追加

- URIs/imas-schema.ttl
> Charactorの継承元をschema系へ変更

- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
> foaf:gender→schema:gender

- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
765AS
CinderellaGirls
MillionStars
DiaryStars
1054Pro
315ProIdols(SideMアイドルの総称無いの？)
> ゲームごとの所属を追加

- RDFs/Unit.rdf
出典:デレステでの表記
さっつんのツイートhttps://twitter.com/DApanda323/status/844078562810331136
> インディヴィジュアルズ→individuals

- URIs/imas-schema.ttl
"imas:"が被ってる(かぶってるとは言ってない)ので一つにする
プロパティが一つ一つが閉じられてないので閉じる
> 文法を正した(DB内に入れるため

- RDFs/CinderellaRanking.rdf
- URIs/imas-schema.ttl
> Cinderella girls election

- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- URIs/imas-schema.ttl
> Million theater days profile

- RDFs/MusicComposition.rdf
- RDFs/Song.rdf
> 書式、MusicCompositionのまとめ方変更

- RDFs/961.rdf
- 玲音は名前とCV以外不明。
- 詩花は年齢身長体重などのプロフィールが公開済み。
- ソース：http://dengekionline.com/elem/000/001/598/1598018/
> 玲音、詩花のプロフィールを追加

- RDFs/Unit.rdf
>  Engage!→Engage%21

- RDFs/SideM.rdf
[ライブオンステージ公式サイト](http://side-m.idolmaster.jp/lo-stage/)より九十九一希のプロフィール
> correct birthDate of 九十九一希

- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
DBpediaでのURIを載せたので、Wikiから抽出された(されてれば)情報に繋げられる
> add CV's URI(in DBpedia)

- RDFs/Live.rdf
> stringとlang:jaの解釈を改めた

- RDFs/Unit.rdf
> Unit correction

- RDFs/Unit.rdf
> add ももぺあべりー、ももぺあ、ももべりー、ぺあべりー、セクシーパンサーズ、ラフ＆フィアーズ

- RDFs/CinderellaGirls.rdf
> add CV:藤本彩花

- RDFs/Unit.rdf
#76 のPR検証が長くて色々masterに追加されたのでrebase
>  add Unit.rdf & alterName & member

- RDFs/Unit.rdf
> add "Angel/Princess Stars","夜想令嬢",,correct "Fairy Stars"

- RDFs/CinderellaGirls.rdf
> fix type of Shimamura_Uzuki's height

- RDFs/283.rdf
- RDFs/Unit.rdf
あとあと、283Proはアイドルの説明があるから追加してみた
> add "L'Antica" & member, "Cleasky"

- RDFs/283.rdf
- RDFs/Unit.rdf
色は紹介リンクのボタンの囲う色から
イルミネカラーズの色はこれでいいのかよくわかんない
>  add "放課後クライマックスガールズ",283ProColors 

- RDFs/CinderellaGirls.rdf
#55 より
6thで変わる？でも今はこれじゃん！ってことで。
6thで増えるだろうなぁ...
> Add cinderella colors,DBpedia URIs

- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/SideM.rdf
> URI:"du" => "zu".

- RDFs/CinderellaRanking.rdf
> CinderellaRankingPerson => CinderellaRankingResult

- RDFs/Staff.rdf
> add Producer.

- RDFs/Clothes.rdf
- RDFs/Unit.rdf
> Correct grateful blue

- RDFs/876.rdf
> fix Ai's birthday

- RDFs/Staff.rdf
> add Misak's Birthday

- RDFs/SideM.rdf
> fix Kyosuke's nameKana

- RDFs/283.rdf
出身地について、都道府県名のうち都と県が付いているレコードがあったため他のレコードに合わせて削除
> 都道府県のうち、都と県を他のレコードに合わせて削除

- RDFs/961.rdf
ミリシタに詩花のプロフィールが出ていたので差分を追加しました。
> update Siika's profile

- RDFs/CinderellaGirls.rdf
> add 南条光's C.V.

- RDFs/Clothes.rdf
> add Million Theater Days's Clothes.

- URIs/imas-schema.ttl
> add "imas:Performance"

- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
ref #169.
忘れてたけど、issue閉じる前なのでセーフ
> "constellation"=>"Constellation"

- .circleci/config.yml
- .circleci/rdflint-config.yml
> add rdflint by circleci

- RDFs/CinderellaGirls.rdf
     ■                
     ■        ■■■■■■■ 
■■■■■■■■■■        ■   
     ■           ■    
   ■■■                
  ■  ■                
  ■  ■       ■■       
   ■■■       ■        
     ■       ■■       
   ■■         ■■■■■■■■
   ■                  
> Add idol "砂塚あきら"

- RDFs/Unit.rdf
ジェットブラック・ウィングス（的場梨沙、新田美波、ナターリア）
シークレット{Cipher},（鷺沢文香、神谷奈緒、大石泉）
フレーズ*ミュルミュール（遊佐こずえ、龍崎薫、的場梨沙、櫻井桃華）
2WINKLE 4OR INFINITY∞（的場梨沙、池袋晶葉、メアリー・コクラン、中野有香）
> 最近モバマスで出たユニットの一部を追加

- RDFs/CinderellaGirls.rdf
> add "夢見りあむ"

- RDFs/CinderellaGirls.rdf
https://github.com/imas/imasparql/issues/202
> 白雪千夜ちゃんと黒崎ちとせちゃん！

- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
move to cute area "白雪千夜","黒埼ちとせ"
ref. #204
> add C.V. resources for Wikidata.org

- RDFs/283.rdf
- RDFs/Unit.rdf
> add straylight

- RDFs/765MillionStars.rdf
- RDFs/SideM.rdf
> add "imas:Hobby=>なし" to ジュリア,都築圭

- RDFs/765MillionStars.rdf
紬ちゃんと歌織さんのパーソナルカラーについて、修正の提案です。
経緯については、こちらをご確認いただけますでしょうか。
https://github.com/imas/rubimas/pull/12
> Fix personal color

- RDFs/283.rdf
> 黛冬優子の紹介文を修正

- .editorconfig
- RDFs/Disc.rdf
- RDFs/Live.rdf
- RDFs/Song.rdf
- URIs/imas-schema.ttl
> Add editorconfig

- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
> xsd:lang="en" += datatype"rdf:langString"

- RDFs/Disc.rdf
- RDFs/MusicComposition.rdf
- RDFs/Song.rdf
> correct schema

- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
> add name in english

- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
> add rdfs:label

- RDFs/SideM.rdf
[このコミット](https://github.com/imas/imasparql/commit/d431b8b3213456c7b99c1d0b7b3282de3d321884#diff-17c355fde79b7fe9bc6aebf866eb6083L301)でみのりさんのフルネームが消えてしまっていたため復元
> みのりさんのフルネーム復元

- RDFs/Live.rdf
> add future live

- RDFs/Live.rdf
> URLエンコード間違い+スペース

- RDFs/CinderellaRanking.rdf
> 第8回CG総選挙結果

- RDFs/CinderellaRanking.rdf
> 第8回シンデレラガールズ総選挙について、各属性別上位5位ランキングより、11〜15位の得票数を追加

- .circleci/config.yml
> 生成したRDFファイルもrdflintのチェック対象に加える

- RDFs/765MillionStars.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
> fix schema:name

- RDFs/CinderellaGirls.rdf
名字が不明な海外勢の英語表記に`undefined`が混じっていたため除去しました。
名字と名前からフルネームを生成したときに混入したものと思いますが一応確認をお願いします。
> schema:name xml:lang="en" から"undefined" を除去

- .circleci/config.yml
- RDFs/283.rdf
- RDFs/CinderellaIntroduction.rdf
- RDFs/Clothes.rdf
- RDFs/Live.rdf
- RDFs/Unit.rdf
以下の対応
- rdflintを0.0.7にverup
- リテラル先頭・末尾の半角スペース除去
rdflint-0.0.7 でリテラル先頭・末尾の半角スペースが無いかのチェックを追加
> リテラル先頭・末尾の半角スペース除去

- RDFs/CinderellaGirls.rdf
> Add 遊佐こずえ's CV

- RDFs/283.rdf
- RDFs/961.rdf
- RDFs/CallTable.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/CinderellaIntroduction.rdf
- RDFs/CinderellaRanking.rdf
- RDFs/Clothes.rdf
- RDFs/Unit.rdf
> Fix idols name

- RDFs/CinderellaGirls.rdf
夢見さんが「せっかくぼくの声が付いたのに P サマやみんなから忘れられちゃう。はー、めっちゃやむ・・・」と嘆いていたので追加しました。
> add Riamu-CV

- RDFs/CinderellaGirls.rdf
漢字が間違っていたので修正しました。
https://www.artsvision.co.jp/talent/4704/
> fix: 立花日菜の漢字間違え

- RDFs/Unit.rdf
「Sunshine Rhythm」「BlueMoon Harmony」「Starlight Melody」が抜けていたので追加しました。
紬・歌織加入後、琴葉存在仕様です。[765MillionStarsに紬・歌織がいる](https://sparql.crssnky.xyz/imasrdf/RDFs/detail/765MillionStars)のと、[スコーピオに琴葉がいる](https://sparql.crssnky.xyz/imasrdf/RDFs/detail/%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%94%E3%82%AA)ので、入れておいたほうが辻褄は合うと思います。
> Add LTF units

- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
参考：https://www.wikidata.org/wiki/Wikidata:Data_access/ja
> Fix Wikidata URIs

- RDFs/CinderellaGirls.rdf
> Add 佐城雪美's CV

- RDFs/Unit.rdf
#290 で追加したユニットの datatype がおかしかったので、ついでに直しました（[UnitCreate](https://sparql.crssnky.xyz/imas/RDFmaker/UnitCreate.html) を直さないとダメみたいです）。
> Add マイティーセーラーズ

- RDFs/876.rdf
CVを追加しました。  
https://github.com/imas/imasparql/pull/299
> Add 桜井夢子 CV

- RDFs/876.rdf
cf. https://github.com/imas/imasparql/pull/300#discussion_r328472708
> Fix WikiData URI

- RDFs/Clothes.rdf
Clothes.rdfに、以下を追加
- ベル・マシェリ 共通衣装に移動、52人分追加
- ハピネスクローバー アナザー２追加
- 以下のユニット衣装追加
- シークレットリップ
- N県K市立高等学校指定制服
- おとぎの国の少女衣装
> Add おとぎの国の少女衣装ほか

- RDFs/SideM.rdf
`imas:cv xml:lang="ja"`の中身がなかったので修正。
> Fix 蒼井享介 CV

- RDFs/CinderellaGirls.rdf
> add ナターリア's C.V. "生田輝"

- RDFs/765AS.rdf
取得しようとしたら定義されていなかったようなので、PRさせて頂きます!!
> [ADD] 如月千早の利き手情報の追加修正

- RDFs/Staff.rdf
ref. https://github.com/imas/imasparql/pull/303#discussion_r329961350
> fix 美咲's age datatype

- RDFs/Unit.rdf
2019/11/01、ドリフで登場
結城晴、佐々木千枝、的場梨沙、古賀小春（全員ウェディングドレス）
https://twitter.com/quanta_1/status/1190253100788940800
> ユニットにフューチャー☆アップを追加

- RDFs/CinderellaGirls.rdf
他のアイドル事務所のドームライブを見てきました！
どのアイドルも可愛かったですし、まさかあの人のDJが聞けるなんて…！不肖音無、感無量ですっ！
Amazon Prime Videoで配信の「[Spin-off!](https://www.amazon.co.jp/%E3%80%90Amazon-co-jp%E9%99%90%E5%AE%9A%E3%80%91-IDOLM-CINDERELLA-GIRLS-8%E5%91%A8%E5%B9%B4%E7%89%B9%E5%88%A5%E4%BC%81%E7%94%BB-Spin-off-%E3%83%88%E3%83%BC%E3%82%AF%E6%98%A0%E5%83%8F%E4%BB%98%E3%81%8D%E3%80%91%E8%B3%BC%E5%85%A5%E7%89%88/dp/B0815T5CQH)」も、移動の新幹線で視聴しています。的場梨沙ちゃんのCVが公開されたので、こちらにPR送らせていただきますね！
ref. #323
> add 的場梨沙's CV

- constrains/ClothesShape.ttl
- constrains/UnitShape.ttl
SHACLのShape定義にタイプミスがあったので、修正しています
> fix typo: sh:close to sh:closed

- RDFs/CinderellaGirls.rdf
> add "小関麗奈"'s CV

- RDFs/SideM.rdf
- URIs/imas-schema.ttl
> change 九十九's CV "比留間俊哉"

- RDFs/Lives/Live_2004.rdf
- RDFs/Lives/Live_2005.rdf
- RDFs/Lives/Live_2006.rdf
- RDFs/Lives/Live_2007.rdf
- RDFs/Lives/Live_2008.rdf
- RDFs/Lives/Live_2009.rdf
- RDFs/Lives/Live_2010.rdf
- RDFs/Lives/Live_2011.rdf
- RDFs/Lives/Live_2012.rdf
- RDFs/Lives/Live_2013.rdf
- RDFs/Lives/Live_2019.rdf
- RDFs/Lives/Live_2020.rdf
既存のやつをEventScheduledにしました。
そして申し訳ないのですが、ファイル分割した際に無くなってしまってたEventCancelledも記入しました
> add EventStatus.

- .github/CODEOWNERS
- URIs配下
- .rdflint配下
- .github配下
- LICENSE
- README.md
に対して、imasparql teamの承認にしました
> add CodeOwners file

- RDFs/Clothes.rdf
Clothes.rdfに、以下を追加
- 笑花祝霰、笑花祝霰+
- リトルコンダクター++
- おとぎの国の魔法使い衣装
> Add clothes: 笑花祝霰、リトルコンダクター++

- RDFs/CinderellaRanking.rdf
> 第9回シンデレラガール総選挙とボイスアイドルオーディション結果

- CONTRIBUTING.md
ref. https://github.com/imas/imasparql/issues/96#issuecomment-660829720
> CONTRIBUTING.mdに、IM@Studyガイドラインへのリンクを追加

- RDFs/Unit.rdf
- ARCANA
- 花咲夜
- Jus-2-Mint
- オペラセリア・煌輝座
> ミリシタのユニットを追加

- RDFs/Clothes.rdf
> MTGシリーズのアナザー衣装の追加

- RDFs/Unit.rdf
イベントページにユニット紹介が生えてた。
ところで、この文章見覚えがあるんですけどどこで見たんでしたっけ....??
> 閃光☆HANABI団の説明を追加

- RDFs/CinderellaGirls.rdf
https://github.com/imas/imasparql/issues/371
本日、辻野あかりちゃんの CV が発表されました。
> add 辻野あかりs CV

- RDFs/CinderellaGirls.rdf
> 追加 レイジーレイジー組の趣味、好きなもの

- RDFs/CallTable.rdf
> 育、星梨花の呼称表を追加

- RDFs/283.rdf
- RDFs/Unit.rdf
> fix ShinyColors's colors

- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- URIs/imas-schema.ttl
- constrains/IdolShape.ttl
ref. #377
サイトのリソース名から、とりあえず英名を入れておくスタイル
> add PopLinks idol's "PopLinksAttribute".

- RDFs/Unit.rdf
15周年はユニット名があるらしい
https://columbia.jp/idolmaster/imasnews/200727.html
> add THE IDOLM@STER FIVE STARS!!!!!

- RDFs/1stVision.rdf
- RDFs/283.rdf
- RDFs/765AS.rdf
- RDFs/765MillionStars.rdf
- RDFs/876.rdf
- RDFs/961.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
- RDFs/Staff.rdf
- RDFs/Xenoglossia.rdf
- URIs/imas-schema.ttl
- constrains/IdolShape.ttl
imas:Titleにて運用していたものが、アイマスでいわゆるブランドという呼び方になったため、変更します。また、SHACLの定義も良い感じにして、誰もが一つ持てる状態にします。
マージ時は事前にSlack等でアナウンスし、期間を設けます。
imas:Titleは、また別の意味を持つ述語にします(それは別PulReq出します)
> TitleからBrandへの変更

- RDFs/Lives/Live_2021.rdf
最初に情報公開されてからだいぶ出演メンバーが増えているのに気づいたので追加しました 😉
> シャニ2nd・3rdの追加出演メンバーの情報を追加

- RDFs/Unit.rdf
ミリオンライブTHE@TER WAVEシリーズのユニットを追加しました。
chicAAmorについてもユニット化は確定とみなしてデータ作成しました。
> THE@TER WAVEシリーズのユニットを追加

- RDFs/Lives/Live_2021.rdf
> シャニ3rd東京 Day2の無観客開催への対応

- RDFs/Unit.rdf
「Blooming Clover」、「Brand New Song」に登場するユニットを追加しました。
> ミリオンライブのコミックに登場するユニットを追加

- RDFs/Units/MillionLive.rdf
lantisCD紹介ページ表記、ゲーム音声、UNIONAIR youtube音声、コミック表記で確認しました。
> ミリオンライブのユニットよみかたを追加

- RDFs/Clothes/ShinyColorsCommon.rdf
- RDFs/Clothes/ShinyColorsUnit.rdf
> シャイニーカラーズの衣装を追加

- RDFs/Clothes/ShinyColorsUnit.rdf
シャイニーカラーズの L’Antica の新衣装「ルフォンドゥ・ラメール」を追加しました
> https://twitter.com/imassc_official/status/1391634858699595777
> ルフォンドゥ・ラメールを追加

- RDFs/CallTable.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/CinderellaGirlsRanking/01/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/02/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/03/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/04/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/05/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/06/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/07/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/08/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/09/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/10/CinderellaRanking.rdf
- RDFs/CinderellaGirlsRanking/CinderellaIntroduction.rdf
- RDFs/Clothes/CinderellaStageCommon.rdf
- RDFs/Clothes/CinderellaStageUnit.rdf
- RDFs/Event.rdf
- RDFs/Units/CinderellaGirls.rdf
close: #432 
- `Tada_Rina` -> `Tada_Riina`
- `TadaRina` -> `TadaRiina`
に修正しました。李衣菜Pのみなさま、申し訳ありませんでした。
> fix to Tada_Riina

- RDFs/283.rdf
> 283プロのアイドルに学年情報を追加

- RDFs/765MillionStars.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
ref. #439
「神崎 蘭子」「二宮 飛鳥」「アスラン=BBⅡ世」
https://twitter.com/imas_poplinks/status/1414185198455902208
https://www.youtube.com/watch?v=3M6ig9C4zYU
属性情報：https://poplinks.idolmaster-official.jp/idol/index.php?sh=true
> 7月登場アイドル3,8月登場アイドル1追加

- RDFs/Units/SideM.rdf
・ユニット名ふりがな(平仮名に統一しています。) #422
・ユニット説明
・C.FIRSTのユニット色(ペンラが出ていないため、サイトを参考に色を仮判断しています。)
いずれもソースはこちら：https://sidem-gs.idolmaster-official.jp/idol/
> sideMユニット情報増強

- RDFs/Clothes/ShinyColorsCommon.rdf
- RDFs/Clothes/ShinyColorsUnit.rdf
- プライベートドレスダウン
- ファウンテンサマー
- ウェイトレス・パスカラ
- デッドチャンネルl2<)3
を追加しました
> シャイニーカラーズの新衣装を追加

- RDFs/Other.rdf
- 出身地
- アイドル名鑑のURL
を追加しました
> アイドル名鑑 : https://idollist.idolmaster-official.jp/detail/240001
> 奥空心白さんのプロフィールを追記

- RDFs/Clothes/ShinyColorsUnit.rdf
シャイニーカラーズ、ノクチルの新衣装 「リップリングクリアマリン」 を追加しました。
> https://twitter.com/imassc_official/status/1436208314430509057
> リップリングクリアマリンを追加

- RDFs/961.rdf
- RDFs/CallTable.rdf
- RDFs/Staff.rdf
- RDFs/Units/765AS.rdf
- RDFs/Units/Other.rdf
#471
亜也の情報源：https://twitter.com/imas_DB/status/1437372978904272898?s=19
ディアマンと呼称の情報源：https://www.famitsu.com/news/202109/13233616.html
ちなみに…
“ディアマント”は、ドイツ語で“ダイヤモンド”の意味があり…
> 亜夜とディアマントを追加

- RDFs/CinderellaGirls.rdf
・西園寺琴歌CV追加：安斎由香里
　https://twitter.com/imascg_chihiro/status/1446717093810884609
> add 西園寺琴歌s CV

- RDFs/SideM.rdf
以下 3 名の `imas:IdolListURL` を追加しました。
- 天峰 秀
- 花園 百々人
- 眉見 鋭心
既存の定義とアイドル名鑑を見比べたところ、趣味に差異があるようですがどうしましょう。あと背景の星がアイドルのイメージカラーだったりするんですかね？
Related: #440
> C.FIRSTのimas:IdolListURLを追加

- RDFs/Clothes/ShinyColorsCommon.rdf
2022/01/01 の更新で実装された、恋鐘さんと甜花さんの衣装を追加しました。
> プライベートドレスダウンを追加

- RDFs/283.rdf
- RDFs/765MillionStars.rdf
- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
> ポプマス追加実装アイドルの属性追加1周年分

- RDFs/283.rdf
謎の使命感
成海さんの名前は2021年以前のライブ出演者の方にもありましたが、こちらは情報として変化しないためそのままにしてあります。
ソース: https://idolmaster-official.jp/news/01_3231.html
> 三峰結華の声優変更への対応

- RDFs/Clothes/ShinyColorsCommon.rdf
シャイニーカラーズの以下の衣装を追加しました。
- ドレスアップパルファム（風野灯織, 八宮めぐる）
> ドレスアップパルファムを追加

- RDFs/CinderellaGirls.rdf
- RDFs/SideM.rdf
https://youtu.be/1zL_yMGm-vw
※ソースは公式のみです
> ポプマス追加実装アイドルの属性データ追加 2022/3

- RDFs/Units/ShinyColors.rdf
- 各ユニットに読み仮名を追加しました (ref. #422)
> シャイニーカラーズのユニットに読み仮名を追加

- RDFs/Clothes/ShinyColorsCommon.rdf
以下の衣装を追加しました。
- ドレスアップパルファム (月岡恋鐘)
- セレスティアルカラーズ
> シャイニーカラーズ 新衣装を追加

- RDFs/Clothes/ShinyColorsCommon.rdf
以下の衣装を追加しました。
- プライベートドレスダウン（風野灯織, 黛冬優子）
> シャイニーカラーズの新規衣装を追加

- RDFs/Clothes/ShinyColorsCommon.rdf
- RDFs/Clothes/ShinyColorsUnit.rdf
> シャイニーカラーズの全体・ユニット衣装を追加

- RDFs/Clothes/ShinyColorsCommon.rdf
- RDFs/Clothes/ShinyColorsUnit.rdf
以下の衣装を追加しました
- リスペクティブワークスタイル（大崎甘奈）
- 紅玉兎ノ装（SHHis）
- ディバインクロンヌ（八宮めぐる）
> シャニの新衣装を追加

- RDFs/SideM.rdf
https://idollist.idolmaster-official.jp/detail/250003
> 鋭心の誕生日・星座を修正

- RDFs/283.rdf
- RDFs/Units/ShinyColors.rdf
ユニットカラーはアイコンの以下の箇所から、Firefox の開発者ツールのスポイトで抽出しました 💄
> add: 斑鳩ルカさんの 283Pro 加入

- RDFs/CinderellaGirls.rdf
望月聖のCV追加：原涼子
https://twitter.com/imascg_stage/status/1605807109030891520
古賀小春のCV追加：小森結梨
https://cinderella-u149-anime.idolmaster-official.jp/staff_cast
> add 望月聖s,古賀小春s CV

- RDFs/283.rdf
公式プロフィールにもある通り4月18日は牡羊座ですね
https://shinycolors.idolmaster.jp/idol/alstroemeria/chiyuki.html
> 千雪さんの星座を修正

- RDFs/Lives/Live_2023.rdf
> add SideM PRS2023

- RDFs/Units/CinderellaGirls.rdf
> U149 (ユニット) の追加

- RDFs/CinderellaGirls.rdf
Shout out Live!!! 出演者のイメージカラーをコンサートカラーから抽出しました(台紙の色を取得)
砂塚あきら：7C8EA2
https://shop.asobistore.jp/products/detail/186395-2_cg-c094-00-00
望月聖：B6DDE4
https://shop.asobistore.jp/products/detail/186395-2_cg-c170-00-00
ライラ：75DED5
https://shop.asobistore.jp/products/detail/186395-2_cg-c186-00-00
> Shout out Live!!! 出演者のイメージカラーを追加

- RDFs/CinderellaGirls.rdf
ライラのCV追加：市ノ瀬加那
https://twitter.com/imascg_stage/status/1674300413330194433
大石泉のCV追加：大木咲絵子
https://twitter.com/imascg_stage/status/1726120721561358479
> add ライラs,大石泉s,イヴ・サンタクロースs CV

- RDFs/Clothes/ShinyColorsCommon.rdf
シャイニーカラーズの服の説明にtypoがあったので、その修正です。
https://dic.pixiv.net/a/%E3%83%9F%E3%83%83%E3%83%89%E3%83%8A%E3%82%A4%E3%83%88%E3%83%A2%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%BC
> fix: Sakuragi_Mano Midnight Monster description

- RDFs/283.rdf
鈴木羽那さんと郁田はるきさんの不足していた分のプロフィールを追加しました
> add: 鈴木羽那さんと郁田はるきさんの不足分のプロフィールを追加

- RDFs/283.rdf
> add: 郁田はるきさんの学年を追加

- RDFs/Gakuen.rdf
- constraints/IdolShape.ttl
以下のサイトを参考に、不足分のプロフィールを追加しました
- [学園アイドルマスター（学マス）｜君と出会い、夢に翔ける](https://gakuen.idolmaster-official.jp/idol/)
- [アイドル検索 | 【公式】アイドルマスターOFFICIAL WEB　-アイドル名鑑‐ (アイマス)](https://idollist.idolmaster-official.jp/search?brand_id_list%5B%5D=6&birth_place=&birth_month=&keyword=&order_type=1&order_direction=1)
- [Xユーザーの学園アイドルマスター【公式】さん: 「／ #学マスノート Vol.6 📖学年・クラス分け一覧 ＼ 初星学園のアイドル科の学年・クラス分けをご紹介✨ #学マス #学園アイドルマスター ＿＿＿＿＿＿＿＿＿＿＿＿ #学園アイドルマスター 👇今すぐ事前登録！ https://t.co/9Bwf8isCZl https://t.co/UiH6Wcwc2x」 / X](https://x.com/gkmas_official/status/1784779649857577310/photo/1)
> 学マスのアイドルの不足分のプロフィールを追加

- RDFs/Gakuen.rdf
https://gakuen.idolmaster-official.jp/idol/lilja/
https://idollist.idolmaster-official.jp/search/detail/60005
> リーリヤのバストサイズ修正

- .github/labeler.yml
ラベルの色はアイドルマスターポータルの CSS の [data-brand=GAKUEN] あたりから取ってます。
> labelerを学マスに対応

- RDFs/Clothes/ShinyColorsCommon.rdf
- RDFs/Clothes/ShinyColorsPersonal.rdf
- RDFs/Clothes/ShinyColorsUnit.rdf
- ドレスアップパルファム
- リスペクティブワークスタイル
- 復刻衣装
- フリスキーサマー
その他、個人衣装・ユニット衣装を追加しました
> add: シャニマスの新衣装を追加

- RDFs/876.rdf
> レトラが21歳になったのでageを変更

- RDFs/Clothes/ShinyColorsUnit.rdf
テディフォローホワイトのwhoseが全部浅倉透になっていたので修正しました…🙏
> fix: TeddyFollowWhiteのwhoseが全部浅倉透になっていた

- RDFs/Gakuen.rdf
- constraints/IdolShape.ttl
十王星南会長と雨夜燕副会長の情報追加です。
https://gakuen.idolmaster-official.jp/idol/sena/
https://gakuen.idolmaster-official.jp/idol/tsubame/
> update 十王星南, add 雨夜燕

- RDFs/876.rdf
愛夏、誕生日おめでとう 🎉 
また、2025/6/23にプロフィールの更新が入り、趣味特技欄が変わっているのでそれも併せて更新します
https://idolmaster-official.jp/va-liv/cosmo
https://idolmaster-official.jp/va-liv/manaka
https://idolmaster-official.jp/va-liv/letora
> 灯里愛夏の年齢を更新 & ヴイアラ3人の趣味・特技を更新
