RDFs/Unit.rdf
add ちびっこ&馬(友情出演)、ビートシューター with 光、怪盗・リサ、怪盗・リサ&執事・オトハ、どうぶつ☆ふぇすた、禁じられた財宝、ファントムキャッツ!、オリジナル・カラーズfeat.和、シング・マイ・ウェイ
梨沙関連のユニットってこんなにあったんですね
=> add some units related to Matoba Risa

RDFs/Event.rdf, RDFs/Unit.rdf
#68 にて
> Unitの方がそのままになってるので伊織は765ASだけど765ProAllstarsには入ってないみたいな妙なことになっている…
と指摘があったので、
```bash
find -type f | grep -v \\.git | xargs sed -i -e "s/Misase/Minase/g"
```
を実行してみました。
確認お願い致します。
=> Fix typo Misase to Minase by find and sed

URIs/imas-schema.ttl
The "imas" prefix is duplicated.
The first value has no effect.
"https://crssnky.xyz/URIs/imas-schema#" is invalid URI.
We can remove `@prefix imas:   <https://crssnky.xyz/URIs/imas-schema#>.` safely.
=> Remove duplicate prefix what is "imas"

RDFs/876.rdf, RDFs/SideM.rdf
同一人物で~年齢~性別と身長が複数取れてしまうのはいろいろ大変なので、ひとまず涼は対応したい。
Ref. #9
=> 876プロの秋月涼と315プロの秋月涼を別人として扱う

.circleci/rdflint-config.yml, RDFs/CinderellaGirls.rdf, RDFs/Staff.rdf
rdflintに姓名の整合ルール追加、その際に発見した誤りの修正
- rdflintのルールに姓名の整合チェックを追加
- イヴ・メアリー・キャシーの姓名が逆になっていたので修正
- 齋藤孝司の姓が「Ssaito」となっていたので修正
```
RDFs/CinderellaGirls.rdf
WARN  姓名整合(和文): 姓名, 姓+名が不一致: イヴ・サンタクロース != イヴサンタクロース|サンタクロースイヴ|サンタクロース・イヴ
WARN  姓名整合(和文): 姓名, 姓+名が不一致(かな): いゔ・さんたくろーす != いゔさんたくろーす|さんたくろーすいゔ|さんたくろーす・いゔ
WARN  姓名整合(和文): 姓名, 姓+名が不一致: メアリー・コクラン != メアリーコクラン|コクランメアリー|コクラン・メアリー
WARN  姓名整合(和文): 姓名, 姓+名が不一致(かな): めありー・こくらん != めありーこくらん|こくらんめありー|こくらん・めありー
WARN  姓名整合(和文): 姓名, 姓+名が不一致: キャシー・グラハム != キャシーグラハム|グラハムキャシー|グラハム・キャシー
WARN  姓名整合(和文): 姓名, 姓+名が不一致(かな): きゃしー・ぐらはむ != きゃしーぐらはむ|ぐらはむきゃしー|ぐらはむ・きゃしー
RDFs/Staff.rdf
WARN  姓名整合(英文): 姓名, 姓+名が不一致: Saito Takashi != Ssaito Takashi|Takashi Ssaito
```
=> 姓名の整合ルール追加、イヴ・メアリー・キャシーの姓名修正

RDFs/Unit.rdf
CD、ゲームともにカタカナ表記だったため
https://www.lantis.jp/imas/release_LACM-14634.html
=> ミリオン、XXスターズのユニット名のカタカナ化

.circleci/rdflint-suppress.yml, RDFs/283.rdf, RDFs/765AS.rdf, RDFs/765MillionStars.rdf, RDFs/876.rdf, RDFs/961.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf, constrains/idol.ttl
ref #294 
`imas:Idol` に対する制約をかける `imas:IdolShape` を追加しました
まずは #294 で上がった述語に対しての制約だけです
=> imas:IdolShapeを追加

.circleci/rdflint-suppress.yml, RDFs/Staff.rdf
https://github.com/imas/imasparql/pull/303#discussion_r329961350 に合わせて、`imas:Staff` も `rdf:langString` の `@ja` に統一しました。
上記の表中で `xsd:string` となっている SideM の都築圭の `foaf:age` は、きりだるまさんの 1402eac で変更されます。このコミットはそれ以外のスタッフの `xsd:string` を `rdf:langString` に変更しています。
=> Change Staff's datatype

RDFs/1stVision.rdf, RDFs/283.rdf, RDFs/765AS.rdf, RDFs/765MillionStars.rdf, RDFs/876.rdf, RDFs/961.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf, URIs/imas-schema.ttl
アイドル名鑑内のアイドル毎URLを追加しました。im@sparqlから何かしらをしてSNSに共有する際などに便利だと思います。
- `876.rdf` 内の一部のアイドルはアイドル名鑑に登録されていなかったためURLも追加していません
- 桜井夢子
- サイネリア
- 東豪寺麗華
- 朝比奈りん
- 三条ともみ
- XML 及び RDF 初心者なので何かミスっているかもしれません (URLへのリンクは `xlink:href` でいいのかとか…)
**DISCLAIMER:** このデータは https://idollist.idolmaster-official.jp/search で devtools を開きDOM構造からURLとアイドル名をいい感じにダンプするJS(自作)を実行して得たJSONを元に生成しました
- これを受け入れるかどうかはいろいろな思想があると思われます
- あくまで私個人的には
- 今回は元からロボットにも読まれがちな HTML がソースとなっているので、ゲームの内部データ等 (参考: https://github.com/imas/imasparql/issues/96#issuecomment-658114460 ) よりは白めだと考えています
- 実際に Google にも既にインデックスされています https://www.google.com/search?q=site%3Aidollist.idolmaster-official.jp
- が、 robots.txt はなんか書きミスみたいな感じなのでうーんという気もします https://idollist.idolmaster-official.jp/robots.txt
- Google の robots.txt テスターでは `Disallow:` …
=> アイドル名鑑のアイドル毎URLを追加

RDFs/1stVision.rdf, RDFs/283.rdf, RDFs/765AS.rdf, RDFs/765MillionStars.rdf, RDFs/876.rdf, RDFs/961.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf
どうやら RDF の世界で外部リンクを貼る時は、リンク先がRDFでなくてもそうでなくても `rdf:resource` を使い、`xlink`等は使わないようです (使わないどころか使うといろいろ不都合がある?)
例として、dbpediaでは `dbpedia-owl:wikiPageExternalLink` タグで普通にHTMLしかないページに `rdf:resource` でリンクを貼っているようです (参考: http://ja.dbpedia.org/data/THE_IDOLM@STER.rdf )
という訳なので、imas:IdolListURLのリンクを `xlink:*` から `rdf:resource` を使うものに置換しました。
=> imas:IdolListURL のリンクを xlink から rdf:resource に変更

RDFs/765MillionStars.rdf
高橋未奈美→髙橋ミナミさんの改名を受けて更新しました。Merge or Close のタイミングはおまかせします。
- DBpedia の URL はそのままにしてあります（「髙橋ミナミ」に情報がないため）。
- Live_2019.rdf にある名前はそのままにしてあります（当時は「高橋未奈美」だったため）。
参考
- https://twitter.com/_agson_/status/1340294711458742272
- https://twitter.com/miiiiiina_cat/status/1340307929115709441
- https://twitter.com/miiiiiina_cat/status/1340310933562769409
=> 高橋未奈美さんが髙橋ミナミさんに改名

RDFs/1stVision.rdf, RDFs/283.rdf, RDFs/765AS.rdf, RDFs/765MillionStars.rdf, RDFs/876.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf, RDFs/Staff.rdf, RDFs/Xenoglossia.rdf
基本的にはゲーム内カードの表記に揃える方向で修正
- 楊菲菲
- メアリー・コクラン
- キャシー・グラハム
- イヴ・サンタクロース
- エミリー・スチュアート
ソース: ゲーム内カード
- ジョセフ・真月
ソース: [アイマス英語版Wiki](https://www.project-imas.com/wiki/Idolmaster:_Xenoglossia#Characters)
=> 英語の名前表記を「名」→「姓」の順に変える

RDFs/Lives/Live_2020.rdf
- オンライン配信のみのライブの扱いをどうするか
- ~`schema:eventAttendanceMode`を新たに利用: https://schema.org/eventAttendanceMode~
- ~これまでのライブに`<schema:eventAttendanceMode rdf:resource="http://schema.org/OfflineEventAttendanceMode" />`を付け足すべき？~
- まだ正式採用されてなかった 😢 : https://github.com/schemaorg/schemaorg/issues/1842
- rdflintにバンドルされているschema.orgが古い説: https://github.com/imas/imasparql/pull/386#issuecomment-750239781
- 場所の情報をどうするか
- 公式サイト上の表記は「ASOBISTAGE（アソビストア）」だったのでとりあえずそのまま転記: https://idolmaster-official.jp/live_event/shinycolors_musicdawn/index.php
- 演者に「高山祐介」を入れるべきか否か
- これまでのデータもアイドル名ではなく演者名を入れていたので特に問題ない
- 番組MCを表すのは`schema:actor`が適切と判断
=> MUSIC DAWNの公演情報を追加

RDFs/Units/MillionLive.rdf
ユニットのよみかたは、lantis CDページ, アイマス公式ブログ、ドラマCD、メモリアルコミュで確認しました。
miraclesonic☆expassionとダイヤモンドダイバー◇のよみかたは確認できませんでした。
=> MTWシリーズユニットのよみがなを追加

RDFs/1stVision.rdf, RDFs/765AS.rdf, RDFs/765MillionStars.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf
ref. #119
デレマスアイドルの学年追記
ソースは下記2つ
https://seesaawiki.jp/imascg/d/%A5%A2%A5%A4%A5%C9%A5%EB%C7%AF%CE%F0%C1%E1%B8%AB%C9%BD#footer-footnote38
https://dic.nicovideo.jp/a/%E3%82%A2%E3%82%A4%E3%83%89%E3%83%AB%E3%83%9E%E3%82%B9%E3%82%BF%E3%83%BC%E3%82%B7%E3%83%B3%E3%83%87%E3%83%AC%E3%83%A9%E3%82%AC%E3%83%BC%E3%83%AB%E3%82%BA%3A%E5%AD%A6%E5%B9%B4%E8%A1%A8
sideMの学年追記
ソース：https://w.atwiki.jp/aniwotawiki/pages/38819.html
765ASの学年表記追記
ソース：https://ja.wikipedia.org/wiki/THE_IDOLM@STER%E3%81%AE%E7%99%BB%E5%A0%B4%E4%BA%BA%E7%89%A9#765%E3%82%A2%E3%82%A4%E3%83%89%E3%83%AB%E5%9F%BA%E6%9C%AC%E3%83%87%E3%83%BC%E3%82%BF%E4%B8%80%E8%A6%A7
ミリマスアイドルの学年追記
ソース：https://greemas.doorblog.jp/archives/53151476.html
いずれも、ソースのサイトで明らかに学年が分かるもののみを追加
=> 765AS、デレマス、ミリマス、sideMのアイドルに学年情報を追加

RDFs/283.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf
ref. #439
対象：「安部 菜々」「渡辺 みのり」「三峰 結華」
https://twitter.com/imas_poplinks/status/1414185198455902208
=> ポプマス追加実装アイドルの属性データ追加 2021/7 実装分2

RDFs/Clothes/PopLinks.rdf
#390
ポプマス衣装のデータを追加します。
一部説明文章が未記載の物がありますが、まずはデータ自体の登録が先ということで一度プルリクします。
データの出どころ：
- Pixiv百科事典 ポップリンクス衣装https://dic.pixiv.net/a/%E3%83%9D%E3%83%83%E3%83%97%E3%83%AA%E3%83%B3%E3%82%AF%E3%82%B9%E8%A1%A3%E8%A3%85
- 謎の猫 Wiki* 衣装一覧
https://wikiwiki.jp/popumas_cat/%E8%A1%A3%E8%A3%85%E4%B8%80%E8%A6%A7
=> ポプマス衣装を追加(一部説明文章未記載有)

RDFs/CinderellaGirls.rdf
・浅利七海CV追加：井上ほの花
　https://twitter.com/imascg_chihiro/status/1428960079462617088
・wikidata追加：
　中澤ミナ⇒https://www.wikidata.org/wiki/Q78773735
　集貝はな⇒https://www.wikidata.org/wiki/Q74548472
・CV予定地追加：西園寺琴歌、八神マキノ
=> add 浅利七海s CV +α

RDFs/283.rdf, RDFs/765MillionStars.rdf, RDFs/CinderellaGirls.rdf
ref. #439
対象：「大和 亜季」「高坂 海美」「有栖川 夏葉」
https://twitter.com/imas_poplinks/status/1433755401527255049
=> ポプマス追加実装アイドルの属性データ追加 2021/9 実装分2

RDFs/283.rdf, RDFs/765MillionStars.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf
ref. #439
対象：「ケイト」「ロコ」「舞田 類」
https://twitter.com/imas_poplinks/status/1441365546893672453
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2021/10,11 実装分

RDFs/765MillionStars.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf
ref. #439
対象：「三好 紗南」「望月 杏奈」「鷹城 恭二」
https://twitter.com/imas_poplinks/status/1464179627727937540
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2021/11 実装分3

RDFs/765MillionStars.rdf, RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf
対象：「前川 みく」「野々原 茜」「猫柳 キリオ」「鷹富士 茄子」「望月 聖」「イヴ・サンタクロース」
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2021/12

RDFs/Clothes/ShinyColorsCommon.rdf, RDFs/Clothes/ShinyColorsUnit.rdf
2021/11/30 の更新で追加された、以下の衣装を追加しました。
- オーバーキャストモノクローム（にちか, 美琴）
- ホーリーナイトケープ（にちか, 美琴）
- プライベートドレスダウン（めぐる, 果穂）
=> シャイニーカラーズの新衣装を追加

RDFs/765MillionStars.rdf, RDFs/CinderellaGirls.rdf
対象：「川島 瑞樹」「佐藤 心」「百瀬 莉緒」
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2022/1

RDFs/283.rdf, RDFs/765MillionStars.rdf, RDFs/CinderellaGirls.rdf
https://www.youtube.com/watch?v=qIhhS9xNpP4
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2022/1_2

RDFs/CinderellaGirls.rdf
https://youtu.be/-PNeG49e_NY
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2022/2

RDFs/283.rdf, RDFs/CinderellaGirls.rdf
https://www.youtube.com/watch?v=uOD-4Rz5oCo
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2022/3

RDFs/Clothes/ShinyColorsCommon.rdf
シャイニーカラーズの以下の衣装を追加しました。
- プライベートドレスダウン（桑山千雪, 福丸小糸）
また、恋鐘さんと甜花ちゃんの衣装ポエムが修正されていたので、対応しました。
> https://mobile.twitter.com/arrow_2nd/status/1510479843208491013
何か意味があったわけじゃなかったんですね……。
=> プライベートドレスダウンの追加・修正

RDFs/CinderellaGirls.rdf
https://www.youtube.com/watch?v=dqOqrW72EPg
※ソースは公式のみです
=> ポプマス追加実装アイドルの属性データ追加 2022/4_2

RDFs/Clothes/ShinyColorsUnit.rdf
アンティーカの新衣装、パピロニアフェリークを追加しました。
> https://mobile.twitter.com/imassc_official/status/1527529804983021568
衣装名の語源は
- [papillon](https://kotobank.jp/frjaword/papillon) ... 蝶
- [feerique](https://kotobank.jp/frjaword/feerique) ... 妖精の, 夢のように美しい
かな...と思ったので、リソース名は `Papillonia_Feerique` としてみました。
=> アンティーカの新衣装を追加

.github/labeler.yml, RDFs/Clothes/ShinyColorsPersonal.rdf
Pデスクの衣装から確認できる、pSRのライブ衣装を追加しました。
`衣装順` で並び替えた際の順に追加しています。
=> シャイニーカラーズの個人衣装を追加

RDFs/CinderellaGirls.rdf, RDFs/SideM.rdf
MOIW2023に出演するメンバーのキャラカラーを追加しました。
色はアソビストアの「MOIW!!!!! 2023公式プロデュースタオル」画像から抽出しました。
抽出した色と参照ページの一覧をリストアップします。
ナターリア
D95E25
https://shop.asobistore.jp/products/detail/178017-cdg_c_nt-00-00
桐生つかさ
B04EC5
https://shop.asobistore.jp/products/detail/178017-cdg_c_tk-00-00
的場梨沙
E31C93
https://shop.asobistore.jp/products/detail/178017-cdg_c_rm-00-00
天峰 秀
1D9ADD
https://shop.asobistore.jp/products/detail/178042-862-00-00
花園 百々人
A2D55E
https://shop.asobistore.jp/products/detail/178042-863-00-00
眉見 鋭心
D72630
https://shop.asobistore.jp/products/detail/178042-864-00-00
=> MOIW2023出演メンバーのキャラカラーを追加

RDFs/CinderellaGirls.rdf
ソースは公式コンサートライト(Constellation Gradation ver.)のストラップの色です。
西園寺琴歌 ECCCCD https://shop.asobistore.jp/products/detail/176488-cdg_c_yzt-00-00
辻野あかり D3161C https://shop.asobistore.jp/products/detail/176488-cdg_c_at-00-00
八神マキノ A9A3E1 https://shop.asobistore.jp/products/detail/176488-cdg_c_yzw-00-00
小関麗奈 9F25B6 https://shop.asobistore.jp/products/detail/176488-cdg_c_rk-00-00
黒埼ちとせ F6303F https://shop.asobistore.jp/products/detail/176488-cdg_c_ck-00-00
=> Twinkle LIVE Constellation Gradation出演メンバーのキャラカラーを追加

RDFs/Clothes/ShinyColorsCommon.rdf, RDFs/Clothes/ShinyColorsPersonal.rdf, RDFs/Clothes/ShinyColorsUnit.rdf
以下の衣装を追加しました
- ドレスアップパルファム（園田智代子）
- リスペクティブワークスタイル（有栖川夏葉）
- エナジーデシデラータ（芹沢あさひ）
- カブリィオブホワイト（ALSTROEMERIA）
- ストラミングブリーチ（西城樹里）
- ドリームオブバタフライ（樋口円香）
- ウィッチクラフトアカデミカル (園田智代子) 
- ストロベリーカバー (芹沢あさひ)
- オートクチュールアルテピエス (月岡恋鐘)
- スローモーヴィメント (風野灯織)
- フィジーサイダーポップ (市川雛菜)
`カブリィ` の語源が分からなかったので、`Kaburyi` としています
=> add: シャイニーカラーズの衣装を追加

RDFs/283.rdf
ユニットカラーと同様の色が、公式サイトのキャラクターの枠線に使用されていたため
=> ルカのイメージカラーを修正

RDFs/Clothes/ShinyColorsCommon.rdf, RDFs/Clothes/ShinyColorsPersonal.rdf, RDFs/Clothes/ShinyColorsUnit.rdf
以下の衣装を追加しました。
- ドレスアップパルファム (西城樹里, 杜野凛世)
- ビヨンドザブルースカイ (斑鳩ルカ)
- パルミエーレインビュー (福丸小糸)
-  リスペクティブワークスタイル (芹沢あさひ, 田中摩美々)
- ブレイキングコーション (斑鳩ルカ) 
- チェリッシュメモリーズ (大崎甘奈)
- スペシャルオンスペシアル (黛冬優子)
- エキサイティーンコレクション(杜野凛世)
- フローウィングベル
- [衣装名の由来によると](https://twitter.com/imassc_official/status/1637763373864738818) `ベル` には Bhel, Belle, Bell がかかっているようなので、`FlowingBhel` として登録していいのかご意見をいただきたい感じがします…
- エクスプロアセラータ (風野灯織)
=> シャニの新衣装を追加

RDFs/Lives/Live_2023.rdf
ミリオン10thライブAct-2に郁原ゆうさんが追加出演されることが発表されました
情報源：https://idolmaster-official.jp/news/01_8407
=> ミリオン10thライブAct-2に郁原ゆうさんを追加

RDFs/Clothes/CinderellaStageUnit.rdf
涼宮ハルヒの憂鬱コラボで追加された「県立北高校制服」のデータ追加です。
`<rdf:Description rdf:about="KenritsuKita_HighSchool_Uniform">` よりももうちょっといいabout名があるような気がしますが、いい解釈の仕方が思いつきませんでした。。。
=> シンデレラガールズの県立北高校制服の衣装データ追加

RDFs/StageForCinderella/2022/StageForCinderella.rdf, URIs/imas-schema.ttl
- ref: #514 
シンデレラガールズのStage for Cinderella 2022の予選A-Dとプレイオフ・本選の結果を追加しました。
提案ベースでこのようなスキーマになっていますが、もっとほかによさそうな形式があればコメントがほしいところです。。
参照: https://sfcinderella2022.idolmaster-official.jp/group/
=> Stage for Cinderella 2022の結果の追加

RDFs/283.rdf, RDFs/Units/ShinyColors.rdf
=> CoMETIKメンバー追加

RDFs/Clothes/ShinyColorsCommon.rdf, RDFs/Clothes/ShinyColorsPersonal.rdf, RDFs/Clothes/ShinyColorsUnit.rdf
以下の衣装を追加しました。
- ドレスアップパルファム(黛冬優子, 和泉愛依)
- リスペクティブワークスタイル (八宮めぐる, 緋田美琴)
- プレゼントフロムエストレア (八宮めぐる)
- エナジーデシデラータ (黛冬優子)
- エキサイティーンコレクション (園田智代子)
- レプラシャートファエンツァ (桑山千雪)
- lepre: https://kotobank.jp/itjaword/lepre
- lasciato: https://kotobank.jp/itjaword/lasciare
- 離れ離れになる、離れる のようなニュアンスかな…と解釈しましたが少し厳しい感じもします
- faenza: https://kotobank.jp/itjaword/Faenza
- アブルマドールダマスカス (有栖川夏葉)
- abrumador: https://kotobank.jp/esjaword/abrumador
- ゴーイング・ストレイト (和泉愛依)
- トコサキノトキワ (杜野凛世)
- リーヴィングスターチス (浅倉透)
=> シャイニーカラーズ (enza) の衣装を追加

RDFs/Gakuen.rdf, constraints/IdolShape.ttl
秦谷美鈴さんのプロデュースが始まってプロフィールが充実したので更新しました
https://gakuen.idolmaster-official.jp/idol/misuzu/
学園アイドルマスターのイベントで「3年1組の修学旅行」内で雨夜燕さんが有村真央さん・十王星南さん・姫崎利波さんとともに行動していたことから、1組所属だと判断しました
=> update 秦谷美鈴, 雨夜燕
